config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'homes#index'
  get 'homes/about' => "homes#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book =Book.new
  end

  def create
    @book = Book.new(book_params)
    # {Book: title:"たいとる", body: "ボディ", user_id: nil.....}
    @book.user_id = current_user.id
    # {User: id:1, email: "e@e", name: "なまえ"........}
    # {Book: title:"たいとる", body: "ボディ", user_id: 1.....}
    if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book)
    else
        #indexアクションと同じ
        @books = Book.all
        render :index
    end
  end


  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>editページです</h1>

app/views/books/index.html.erb
<div class="row">
  
  <div class="col-xs-3">
    
    <h2>New Book</h2>
      <!--バリデーションメッセージ-->
  
    <%= form_with model:@book, local:true do |f| %>
    
      <h4>Title</h4>
      <%= f.text_field :title %>
    
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      
      <%= f.submit 'Create Book' %>
    
    <% end %>
    
  </div>
  
  
  <div class="col-xs-9">
    
    <h1>Books</h1>
  
    <section class ="book-box">
      
        <!--<div class="record">-->
        <!--  <div class ="title-contents b"></div>-->
        <!--  <div class ="body-contents b"></div>-->
        <!--  <div class ="button-contents b">-->
        <!--  </div>-->
        <!--</div>-->
      
      <table>
        　<tr align="center">
        　　<th width ="185">title</th>
        　　<th width ="300">body</th>
        　</tr>
        <% @books.each do |book| %>
        　<tr>
        　　<td><%= book.title %></td>
        　　<td><%= book.body %></td>
          　  <th>
            　　  <%= link_to "show", book_path(book) %>
                <%= link_to "edit", edit_book_path(book) %>
                <%= link_to "Destroy", book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %>
        　　    </th>
        　</tr>
        <% end %>
      </table>
  
    </section>
    
  </div>
  
</div>

app/views/books/new.html.erb
<h1>New Book</h1>


<%= form_with model:@book, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

  <% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h6>errors prohibited this book from being saved:</h6>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>


<b>Title</b>:<%= @book.title %>
<b>Boby</b>:<%= @book.body %>


 <%= link_to "Edit", edit_book_path(@book) %>
 <%= link_to "Back", '/books' %>

app/views/homes/about.html.erb
<h1>About</h1>

app/views/homes/index.html.erb
<!--Bootstrapからボタンの配置-->

<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>

    <p>In <i class="fas fa-book"></i><b>Bookers,</b></p>
    <p></p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>


   <!--ボタン配置-->

    <a href ='/users/sign_in'><button type="button" class="btn btn-info col-xs-10 col-xs-offset-1">Log in</button></a>
    <a href ='/users/sign_up'><button type="button" class="btn btn-success col-xs-10 col-xs-offset-1">Sign Up</button></a>

    <%= link_to "Log in", new_user_session_path %>
    <%= link_to "Sing Up", new_user_registration_path %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <!--Required meta tags -->
    <meta charset="utf-8">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->

    <script src="https://kit.fontawesome.com/45c58c3b7f.js" crossorigin="anonymous"></script>

     <!--Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>ブッカーズ</title>
  </head>

  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Bookers</a>
    <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="fas fa-home"></i>Home</a>
            </li>
            <li class="nav-item">
                <%= link_to "About", homes_about_path %>
                <a class="nav-link" href="#"><i class="fas fa-link"></i>About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fas fa-edit"></i>Sign up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fas fa-sign-in-alt"></i>login</a>
            </li>
            <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
        </ul>
    </div>
    </nav>

    <div class="container">

        <%= yield %>
        <div align="right">CopyRight Infratop.inc</d>



        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </div>
  </body>
</html>